import React from "react";
import { motion } from "framer-motion";
import { FileText, Scale, Shield, AlertTriangle, CreditCard, Users } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Terms = () => {
  const sections = [
    {
      title: "Acceptance of Terms",
      icon: Scale,
      content: [
        {
          subtitle: "Agreement",
          text: "By accessing or using NEXORA's services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services."
        },
        {
          subtitle: "Modifications",
          text: "We reserve the right to modify these terms at any time. We will notify users of any material changes, and continued use of our services constitutes acceptance of the modified terms."
        }
      ]
    },
    {
      title: "Use of Services",
      icon: Users,
      content: [
        {
          subtitle: "Permitted Use",
          text: "You may use NEXORA's services for lawful business purposes only. You agree not to use our services for any illegal, harmful, or unauthorized activities."
        },
        {
          subtitle: "Account Responsibility",
          text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
        },
        {
          subtitle: "Prohibited Activities",
          text: "You may not: (a) reverse engineer our software, (b) attempt to gain unauthorized access to our systems, (c) use our services to create competing products, or (d) violate any applicable laws or regulations."
        }
      ]
    },
    {
      title: "Intellectual Property",
      icon: Shield,
      content: [
        {
          subtitle: "Our IP Rights",
          text: "NEXORA and its licensors own all rights, title, and interest in and to the services, including all intellectual property rights. Our services are protected by copyright, trademark, and other laws."
        },
        {
          subtitle: "Your Content",
          text: "You retain ownership of the content you create using our services. However, you grant us a license to use, modify, and display your content as necessary to provide our services."
        },
        {
          subtitle: "Generated Content",
          text: "Content generated by our AI belongs to you, but we may use anonymized and aggregated data to improve our services and train our models."
        }
      ]
    },
    {
      title: "Payment Terms",
      icon: CreditCard,
      content: [
        {
          subtitle: "Subscription Fees",
          text: "Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law or as specifically stated in our refund policy."
        },
        {
          subtitle: "Price Changes",
          text: "We may change our pricing at any time. We will provide at least 30 days' notice of any price increases for existing subscribers."
        },
        {
          subtitle: "Payment Processing",
          text: "Payments are processed by third-party payment processors. You agree to their terms and conditions in addition to ours."
        }
      ]
    },
    {
      title: "Disclaimers and Limitations",
      icon: AlertTriangle,
      content: [
        {
          subtitle: "Service Availability",
          text: "We strive to maintain high availability but do not guarantee uninterrupted access to our services. We may suspend or terminate services for maintenance, updates, or other operational reasons."
        },
        {
          subtitle: "AI-Generated Content",
          text: "Our AI-generated content is provided for informational purposes only. We do not guarantee the accuracy, completeness, or suitability of AI-generated business plans, market research, or other content."
        },
        {
          subtitle: "Limitation of Liability",
          text: "To the maximum extent permitted by law, NEXORA shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of our services."
        }
      ]
    },
    {
      title: "Termination",
      icon: FileText,
      content: [
        {
          subtitle: "Termination by You",
          text: "You may terminate your account at any time by contacting us or using the account deletion feature in your settings."
        },
        {
          subtitle: "Termination by Us",
          text: "We may suspend or terminate your account if you violate these terms, engage in fraudulent activity, or for other legitimate business reasons."
        },
        {
          subtitle: "Effect of Termination",
          text: "Upon termination, your right to use our services will cease immediately. We may retain certain information as required by law or for legitimate business purposes."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <Navbar />
      
      {/* Hero Section */}
      <section className="pt-24 pb-16 bg-gradient-to-br from-white via-gray-50 to-pulse-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <div className="inline-flex items-center px-4 py-2 rounded-full text-sm font-medium bg-pulse-100 dark:bg-pulse-900/30 text-pulse-600 dark:text-pulse-400 border border-pulse-200 dark:border-pulse-800 mb-6">
              <FileText className="w-4 h-4 mr-2" />
              <span>Terms of Service</span>
            </div>
            
            <h1 className="text-4xl md:text-5xl font-display font-bold mb-6 bg-gradient-to-r from-gray-900 via-pulse-600 to-gray-900 dark:from-white dark:via-pulse-400 dark:to-white bg-clip-text text-transparent">
              Terms of Service
            </h1>
            
            <p className="text-xl text-gray-600 dark:text-gray-400 leading-relaxed">
              These terms govern your use of NEXORA's AI-powered startup generation platform and services.
            </p>
            
            <div className="mt-8 text-sm text-gray-500 dark:text-gray-400">
              Last updated: January 1, 2025
            </div>
          </motion.div>
        </div>
      </section>

      {/* Content Sections */}
      <section className="py-16 bg-white dark:bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-16">
            {sections.map((section, index) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="relative"
                >
                  <div className="flex items-center mb-8">
                    <div className="inline-flex p-3 bg-pulse-100 dark:bg-pulse-900/30 rounded-xl mr-4">
                      <Icon className="w-6 h-6 text-pulse-600 dark:text-pulse-400" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-display font-bold text-gray-900 dark:text-white">
                      {section.title}
                    </h2>
                  </div>

                  <div className="space-y-6">
                    {section.content.map((item, itemIndex) => (
                      <div key={itemIndex} className="bg-gray-50 dark:bg-gray-800 rounded-xl p-6">
                        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                          {item.subtitle}
                        </h3>
                        <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                          {item.text}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Important Notices */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-16 space-y-8"
          >
            <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-xl p-6 border border-yellow-200 dark:border-yellow-800">
              <h3 className="text-lg font-semibold text-yellow-900 dark:text-yellow-100 mb-3 flex items-center">
                <AlertTriangle className="w-5 h-5 mr-2" />
                Important Notice
              </h3>
              <p className="text-yellow-800 dark:text-yellow-200">
                NEXORA provides AI-generated content for informational purposes only. Always consult with qualified professionals before making important business decisions based on our generated content.
              </p>
            </div>

            <div className="bg-blue-50 dark:bg-blue-900/20 rounded-xl p-6 border border-blue-200 dark:border-blue-800">
              <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-100 mb-3">
                Governing Law
              </h3>
              <p className="text-blue-800 dark:text-blue-200">
                These Terms of Service are governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.
              </p>
            </div>

            <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-6 border border-green-200 dark:border-green-800">
              <h3 className="text-lg font-semibold text-green-900 dark:text-green-100 mb-3">
                Dispute Resolution
              </h3>
              <p className="text-green-800 dark:text-green-200">
                Any disputes arising from these terms will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
              </p>
            </div>
          </motion.div>

          {/* Contact Section */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-16 bg-gradient-to-r from-pulse-500 to-pulse-600 rounded-2xl p-8 text-center text-white"
          >
            <h2 className="text-2xl font-bold mb-4">Questions About These Terms?</h2>
            <p className="text-lg mb-6 opacity-90">
              If you have any questions about these Terms of Service, please don't hesitate to contact us.
            </p>
            <a
              href="/contact"
              className="inline-flex items-center bg-white text-pulse-600 font-semibold px-6 py-3 rounded-full hover:bg-gray-100 transition-colors"
            >
              Contact Legal Team
            </a>
          </motion.div>

          {/* Severability */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-16 text-center text-gray-600 dark:text-gray-400"
          >
            <p className="text-sm">
              If any provision of these Terms of Service is found to be unenforceable or invalid, 
              that provision will be limited or eliminated to the minimum extent necessary so that 
              these Terms of Service will otherwise remain in full force and effect.
            </p>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Terms;
